# Generated by Django 6.1 on 2026-08-14 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_number', models.CharField(max_length=17)),
                ('citizenship_front_image', models.ImageField(upload_to='kyc_documents/')),
                ('citizenship_back_image', models.ImageField(upload_to='kyc_documents/')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.profile')),
            ],
        ),
    ]
